### ISSUE TITLE
[BUG] (Broken clock after major Windows 11 update)

### ISSUE THREAD

**Issue by Nekrux** [marticliment/ElevenClock#1270] opened 2023-10-08 15:18 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [x] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

The issue seems similar to a previous [one](https://github.com/marticliment/ElevenClock/issues/1209) I already encountered in the past. 

Basically notifications broke ElevenClock. It worked like a charm before last Windows update (KB5030310). Actually I'm running on: Windows 11 Pro 22H2 22621.2361

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.02004528045654297 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.0 (v4.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "it"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1721, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🟢 Loaded clocks in 1.2075316905975342
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 130, in __init__

🔴   File ".\settings.py", line 130, in __init__

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 Note this traceback was caught by reporter and has been added to the log (cannot access local variable 'langName' where it is not associated with a value)
🔵 Language file up-to-date
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.2073802947998047
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1721, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(441, 434, 200, 46)
🔵 Full screen rect:  (0, 0, 640, 480)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Restart loop: 1
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1721, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
Action: ('win', 'n')
Action: ('win', 'n')
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/e/levenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
Action: ('win', 'n')
Action: ('win', 'n')
Action: ('win', 'n')
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
Action: ('win', 'n')
Action: ('win', 'n')
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
Action: ('win', 'n')
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Copying log to the clipboard...
```

### Screenshots and videos

![immagine](https://github.com/marticliment/ElevenClock/assets/11512054/3b022357-e277-4fa6-ba38-9a6ce43664cb)
![immagine](https://github.com/marticliment/ElevenClock/assets/11512054/3dab952c-35f5-405a-abb3-3b704786af19)

**Comment by marticliment** [comment] 2023-10-09 14:51
duplicate of #1228

**Closed** 2023-10-09 14:52 UTC
Labels: bug, triage
