### ISSUE TITLE
[Lunar Calendar] (Please add an option where a user can choose or show what date is today in lunar calendar)

### ISSUE THREAD

**Issue by markipler0210** [marticliment/ElevenClock#1331] opened 2024-04-05 03:25 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Please think about how to make people see the lunar calendar

### Describe how this new feature could help users.

We are the Asians and we need to know what date is today in lunar calendar

**Comment by marticliment** [comment] 2024-04-05 09:42
duplicate of #1151

**Closed** 2024-04-05 09:42 UTC
Labels: new-feature, triage
