### ISSUE TITLE
[BUG] 200+ elevenclock instances after windows L

### ISSUE THREAD

**Issue by Rajdave69** [marticliment/ElevenClock#1212] opened 2023-07-04 11:32 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [x] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Over 200+ elevenclock instances have appeared after i logged into my PC after a ctrl + L.

Initially, the taskbar was broken so I had to restart explorer.exe with task manager. And looks like elevenclock went crazy during taskbar being broken

### Steps to reproduce the issue

Not really sure honestly, you need to log into the PC while taskbar crashes, then only this occurs

### ElevenClock Log

```text
🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3042, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 403: Forbidden

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3051, in loadAnnouncements

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)

🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 140, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
```

### Screenshots and videos

![image](https://github.com/marticliment/ElevenClock/assets/86198810/852f78c7-2eca-4150-bcfe-10dbbc8cddc7)

**Comment by marticliment** [comment] 2023-07-04 17:21
Hello,

can you please post your ElevenClock version?

**Comment by Rajdave69** [comment] 2023-07-05 11:30
Version 3.9.6

**Comment by marticliment** [comment] 2023-07-05 12:50
Please upgrade to version 4.2.0 manually. The updater broke on 3.x.x due to issues with the old domain

**Comment by Rajdave69** [comment] 2023-07-05 15:26
Done so, will tell if any more issues occur

**Comment by Rajdave69** [comment] 2023-07-05 18:14
Update, the app crashed _once_ this time, after opening from win+L i saw one empty window with an empty button

**Comment by Rajdave69** [comment] 2023-07-18 19:45
app crashes every time windows explorer restarts on logging in after win+l

**Comment by totallytavi** [comment] 2023-07-28 04:40
I have a similar issue to this. ElevenClock has randomly been starting instances of itself. I don't see it happening until my computer slows down and I spot multiple instances open. Screenshot below for reference. All of them seem to be "idle" and never respond
![image](https://github.com/marticliment/ElevenClock/assets/66774833/8f3e73ca-2be6-4e2f-9eea-12d5ddda6a23)

My log shows nothing wrong (One error but that was due to "could not find addr" which is Internet related).

**Comment by marticliment** [comment] 2023-07-29 17:38
@totallytavi, which version of ElevenClock are you running?

**Comment by totallytavi** [comment] 2023-08-06 00:13
Using version 4.2.2. In an attempt to solve this issue, I ticked on the option called "Reload clocks every 5 minutes". The issue has since disappeared. For the sake of testing, I'm going to disable it and report back in 1-2 days.

**Comment by marticliment** [comment] 2023-08-31 11:38
Hello @totallytavi, was your issue fixed?

**Comment by totallytavi** [comment] 2023-09-02 20:32
It appears the issue is fixed now.

**Comment by Rajdave69** [comment] 2023-09-04 18:21
![image](https://github.com/marticliment/ElevenClock/assets/86198810/6ba270c0-8efe-4d1b-8fb0-480d948ac9ee)

Happened on 4.3.0

**Comment by Rajdave69** [comment] 2023-09-04 18:25
[logtoday.txt](https://github.com/marticliment/ElevenClock/files/12515928/logtoday.txt)
log file btw

**Comment by totallytavi** [comment] 2023-12-02 06:28
![image](https://github.com/marticliment/ElevenClock/assets/66774833/f20e65a2-cc42-4913-a352-0f36e1cb50e2)
![image](https://github.com/marticliment/ElevenClock/assets/66774833/63e685ed-998e-416a-b063-a835ce5b7e65)
Yikes, it happened again!

**Comment by totallytavi** [comment] 2023-12-02 06:31
Not sure why GitHub makes the first few lines of my log giant but alright...

**Comment by marticliment** [comment] 2023-12-02 10:20
Yes, I agree on what @Naolador said.

Please uninstall ElevenClock and then delete a folder named .elevenclock located under your user directory.

Then attempt to reinstall.

**Closed** 2023-12-28 09:02 UTC
Labels: bug, pending
